/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ActionSize: typeof import('@/design-system/token').ActionSize
  const Activity: typeof import('react').Activity
  const AspectRatio: typeof import('@/legacy-design-system/token').AspectRatio
  const BorderWidth: typeof import('@/legacy-design-system/token').BorderWidth
  const ButtonSize: typeof import('@/design-system/token').ButtonSize
  const Color: typeof import('@/design-system/token').Color
  const ContainerSize: typeof import('@/legacy-design-system/token').ContainerSize
  const Duration: typeof import('@/design-system/token').Duration
  const Ease: typeof import('@/design-system/token').Ease
  const Elevation: typeof import('@/legacy-design-system/token').Elevation
  const Font: typeof import('@/design-system/token').Font
  const FontSize: typeof import('@/legacy-design-system/token').FontSize
  const Fragment: typeof import('react').Fragment
  const Frame: typeof import('@/design-system/Frame/Frame').Frame
  const IconSize: typeof import('@/legacy-design-system/token').IconSize
  const InputSize: typeof import('@/design-system/token').InputSize
  const Layout: typeof import('@/design-system/Frame/Layout/Layout').Layout
  const LineHeight: typeof import('@/legacy-design-system/token').LineHeight
  const Opacity: typeof import('@/legacy-design-system/token').Opacity
  const Radius: typeof import('@/legacy-design-system/token').Radius
  const Radius2: typeof import('@/design-system/token').Radius2
  const Shadow: typeof import('@/design-system/token').Shadow
  const Size: typeof import('@/legacy-design-system/token').Size
  const Space: typeof import('@/legacy-design-system/token').Space
  const Stroke: typeof import('@/design-system/token').Stroke
  const Suspense: typeof import('react').Suspense
  const ZIndex: typeof import('@/legacy-design-system/token').ZIndex
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const forwardRef: typeof import('react').forwardRef
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const startTransition: typeof import('react').startTransition
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useMemo: typeof import('react').useMemo
  const useOptimistic: typeof import('react').useOptimistic
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
}
