/**
 * IDDL Section Specification (v5 draft)
 *
 * Defines categories, design contexts, and compatibility rules for all Section roles.
 */

import type {
  SectionCategory,
  SectionDesignContext,
  SectionRole,
  SectionRules,
} from '../Section.types';

/**
 * Section Role Categories
 */
export const SECTION_CATEGORIES: Record<SectionRole, SectionCategory> = {
  Header: 'bar',
  Footer: 'bar',
  Toolbar: 'bar',
  Statusbar: 'bar',
  Tabbar: 'bar',
  Sidebar: 'panel',
  Aside: 'panel',
  Panel: 'panel',
  Rail: 'panel',
  Main: 'main',
  Canvas: 'main',
  Content: 'main',
  Modal: 'overlay',
  Drawer: 'overlay',
  Sheet: 'overlay',
  Popover: 'overlay',
  Toast: 'overlay',
  Navigation: 'landmark',
  Search: 'landmark',
  Region: 'landmark',

  // Aliases & Extensions (Mapped to categories)
  Navigator: 'panel', // Legacy alias
  Container: 'main', // Legacy alias
  ActivityBar: 'panel', // IDE Extension (Rail-like)
  UtilityBar: 'bar', // IDE Extension
  PrimarySidebar: 'panel', // IDE Extension
  SecondarySidebar: 'panel', // IDE Extension
  Editor: 'main', // IDE Extension
  Master: 'panel', // IDE Extension
  Detail: 'panel', // IDE Extension
  DialogHeader: 'bar', // Modal part
  DialogContent: 'main', // Modal part
  DialogFooter: 'bar', // Modal part
  Nav: 'landmark',
  Status: 'bar',
  Dock: 'bar',
};

/**
 * Default Design Contexts
 */
export const SECTION_DESIGN_CONTEXTS: Record<SectionRole, SectionDesignContext> = {
  // === Bar Category ===
  Header: {
    role: 'Header',
    type: 'Bar',
    direction: 'horizontal',
    sizeMode: 'fixed',
    scrollAxis: 'none',
    defaultDensity: 'Compact',
    allowHero: false,
    maxDepth: 2,
    preferIconOnly: true,
    truncateText: true,
    tooltipRequired: true,
    layer: 'base',
    collapsible: false,
    resizable: false,
    focusTrap: false,
  },
  Footer: {
    role: 'Footer',
    type: 'Bar',
    direction: 'horizontal',
    sizeMode: 'fixed',
    scrollAxis: 'none',
    defaultDensity: 'Compact',
    allowHero: false,
    maxDepth: 2,
    preferIconOnly: false,
    truncateText: true,
    tooltipRequired: false,
    layer: 'base',
    collapsible: false,
    resizable: false,
    focusTrap: false,
  },
  Toolbar: {
    role: 'Toolbar',
    type: 'Bar',
    direction: 'horizontal',
    sizeMode: 'fixed',
    scrollAxis: 'none',
    defaultDensity: 'Compact',
    allowHero: false,
    maxDepth: 1,
    preferIconOnly: true,
    truncateText: true,
    tooltipRequired: true,
    layer: 'base',
    collapsible: false,
    resizable: false,
    focusTrap: false,
  },
  Statusbar: {
    role: 'Statusbar',
    type: 'Bar',
    direction: 'horizontal',
    sizeMode: 'fixed',
    scrollAxis: 'none',
    defaultDensity: 'Compact',
    allowHero: false,
    maxDepth: 1,
    preferIconOnly: false,
    truncateText: true,
    tooltipRequired: false,
    layer: 'base',
    collapsible: false,
    resizable: false,
    focusTrap: false,
  },
  Tabbar: {
    role: 'Tabbar',
    type: 'Bar',
    direction: 'horizontal',
    sizeMode: 'fixed',
    scrollAxis: 'none',
    defaultDensity: 'Compact',
    allowHero: false,
    maxDepth: 1,
    preferIconOnly: true,
    truncateText: true,
    tooltipRequired: true,
    layer: 'base',
    collapsible: false,
    resizable: false,
    focusTrap: false,
  },

  // === Panel Category ===
  Sidebar: {
    role: 'Sidebar',
    type: 'Panel',
    direction: 'vertical',
    sizeMode: 'narrow',
    scrollAxis: 'y',
    defaultDensity: 'Compact',
    allowHero: false,
    maxDepth: 3,
    preferIconOnly: false,
    truncateText: true,
    tooltipRequired: false,
    layer: 'base',
    collapsible: true,
    resizable: false,
    focusTrap: false,
  },
  Aside: {
    role: 'Aside',
    type: 'Panel',
    direction: 'vertical',
    sizeMode: 'medium',
    scrollAxis: 'y',
    defaultDensity: 'Standard',
    allowHero: false,
    maxDepth: 4,
    preferIconOnly: false,
    truncateText: false,
    tooltipRequired: false,
    layer: 'base',
    collapsible: true,
    resizable: true,
    focusTrap: false,
  },
  Panel: {
    role: 'Panel',
    type: 'Panel',
    direction: 'vertical',
    sizeMode: 'medium',
    scrollAxis: 'y',
    defaultDensity: 'Standard',
    allowHero: false,
    maxDepth: 4,
    preferIconOnly: false,
    truncateText: false,
    tooltipRequired: false,
    layer: 'base',
    collapsible: true,
    resizable: true,
    focusTrap: false,
  },
  Rail: {
    role: 'Rail',
    type: 'Rail',
    direction: 'vertical',
    sizeMode: 'fixed',
    scrollAxis: 'y',
    defaultDensity: 'Compact',
    allowHero: false,
    maxDepth: 1,
    preferIconOnly: true,
    truncateText: true,
    tooltipRequired: true,
    layer: 'base',
    collapsible: false,
    resizable: false,
    focusTrap: false,
  },

  // === Main Category ===
  Main: {
    role: 'Main',
    type: 'Stage',
    direction: 'vertical',
    sizeMode: 'flexible',
    scrollAxis: 'y',
    defaultDensity: 'Comfortable',
    allowHero: true,
    maxDepth: 0, // unlimited
    preferIconOnly: false,
    truncateText: false,
    tooltipRequired: false,
    layer: 'base',
    collapsible: false,
    resizable: false,
    focusTrap: false,
  },
  Canvas: {
    role: 'Canvas',
    type: 'Stage',
    direction: 'none',
    sizeMode: 'flexible',
    scrollAxis: 'both',
    defaultDensity: 'Comfortable',
    allowHero: true,
    maxDepth: 0,
    preferIconOnly: false,
    truncateText: false,
    tooltipRequired: false,
    layer: 'base',
    collapsible: false,
    resizable: false,
    focusTrap: false,
  },
  Content: {
    role: 'Content',
    type: 'Stage',
    direction: 'vertical',
    sizeMode: 'readable',
    scrollAxis: 'y',
    defaultDensity: 'Comfortable',
    allowHero: true,
    maxDepth: 0,
    preferIconOnly: false,
    truncateText: false,
    tooltipRequired: false,
    layer: 'base',
    collapsible: false,
    resizable: false,
    focusTrap: false,
  },

  // === Overlay Category ===
  Modal: {
    role: 'Modal',
    type: 'Layer',
    direction: 'vertical',
    sizeMode: 'medium',
    scrollAxis: 'y',
    defaultDensity: 'Comfortable',
    allowHero: true,
    maxDepth: 4,
    preferIconOnly: false,
    truncateText: false,
    tooltipRequired: false,
    layer: 'modal',
    collapsible: false,
    resizable: false,
    focusTrap: true,
  },
  Drawer: {
    role: 'Drawer',
    type: 'Layer',
    direction: 'vertical',
    sizeMode: 'narrow',
    scrollAxis: 'y',
    defaultDensity: 'Standard',
    allowHero: false,
    maxDepth: 3,
    preferIconOnly: false,
    truncateText: true,
    tooltipRequired: false,
    layer: 'overlay',
    collapsible: false,
    resizable: false,
    focusTrap: true,
  },
  Sheet: {
    role: 'Sheet',
    type: 'Layer',
    direction: 'vertical',
    sizeMode: 'flexible',
    scrollAxis: 'y',
    defaultDensity: 'Standard',
    allowHero: false,
    maxDepth: 3,
    preferIconOnly: false,
    truncateText: false,
    tooltipRequired: false,
    layer: 'overlay',
    collapsible: false,
    resizable: true,
    focusTrap: true,
  },
  Popover: {
    role: 'Popover',
    type: 'Float',
    direction: 'vertical',
    sizeMode: 'auto',
    scrollAxis: 'none',
    defaultDensity: 'Compact',
    allowHero: false,
    maxDepth: 2,
    preferIconOnly: false,
    truncateText: false,
    tooltipRequired: false,
    layer: 'popover',
    collapsible: false,
    resizable: false,
    focusTrap: false,
  },
  Toast: {
    role: 'Toast',
    type: 'Float',
    direction: 'vertical',
    sizeMode: 'auto',
    scrollAxis: 'none',
    defaultDensity: 'Compact',
    allowHero: false,
    maxDepth: 1,
    preferIconOnly: false,
    truncateText: true,
    tooltipRequired: false,
    layer: 'toast',
    collapsible: false,
    resizable: false,
    focusTrap: false,
  },

  // === Landmark Category ===
  Navigation: {
    role: 'Navigation',
    type: 'Rail', // Default to Rail, can be Bar
    direction: 'horizontal',
    sizeMode: 'auto',
    scrollAxis: 'none',
    defaultDensity: 'Compact',
    allowHero: false,
    maxDepth: 2,
    preferIconOnly: false,
    truncateText: true,
    tooltipRequired: false,
    layer: 'base',
    collapsible: false,
    resizable: false,
    focusTrap: false,
  },
  Search: {
    role: 'Search',
    type: 'Bar',
    direction: 'vertical',
    sizeMode: 'medium',
    scrollAxis: 'y',
    defaultDensity: 'Standard',
    allowHero: false,
    maxDepth: 3,
    preferIconOnly: false,
    truncateText: false,
    tooltipRequired: false,
    layer: 'base',
    collapsible: false,
    resizable: false,
    focusTrap: false,
  },
  Region: {
    role: 'Region',
    type: 'Stage',
    direction: 'vertical',
    sizeMode: 'flexible',
    scrollAxis: 'y',
    defaultDensity: 'Standard',
    allowHero: false,
    maxDepth: 4,
    preferIconOnly: false,
    truncateText: false,
    tooltipRequired: false,
    layer: 'base',
    collapsible: false,
    resizable: false,
    focusTrap: false,
  },

  // === Aliases & Extensions (Fallback Defaults) ===
  Navigator: {
    role: 'Navigator',
    type: 'Panel',
    direction: 'vertical',
    sizeMode: 'narrow',
    scrollAxis: 'y',
    defaultDensity: 'Compact',
    allowHero: false,
    maxDepth: 3,
    preferIconOnly: false,
    truncateText: true,
    tooltipRequired: false,
    layer: 'base',
    collapsible: true,
    resizable: false,
    focusTrap: false,
  },
  Container: {
    role: 'Container',
    type: 'Stage',
    direction: 'vertical',
    sizeMode: 'flexible',
    scrollAxis: 'y',
    defaultDensity: 'Comfortable',
    allowHero: true,
    maxDepth: 0,
    preferIconOnly: false,
    truncateText: false,
    tooltipRequired: false,
    layer: 'base',
    collapsible: false,
    resizable: false,
    focusTrap: false,
  },
  ActivityBar: {
    role: 'ActivityBar',
    type: 'Rail',
    direction: 'vertical',
    sizeMode: 'fixed',
    scrollAxis: 'y',
    defaultDensity: 'Compact',
    allowHero: false,
    maxDepth: 1,
    preferIconOnly: true,
    truncateText: true,
    tooltipRequired: true,
    layer: 'base',
    collapsible: false,
    resizable: false,
    focusTrap: false,
  },
  UtilityBar: {
    role: 'UtilityBar',
    type: 'Bar',
    direction: 'horizontal',
    sizeMode: 'fixed',
    scrollAxis: 'none',
    defaultDensity: 'Compact',
    allowHero: false,
    maxDepth: 1,
    preferIconOnly: true,
    truncateText: true,
    tooltipRequired: false,
    layer: 'base',
    collapsible: false,
    resizable: false,
    focusTrap: false,
  },
  PrimarySidebar: {
    role: 'PrimarySidebar',
    type: 'Panel',
    direction: 'vertical',
    sizeMode: 'narrow',
    scrollAxis: 'y',
    defaultDensity: 'Compact',
    allowHero: false,
    maxDepth: 3,
    preferIconOnly: false,
    truncateText: true,
    tooltipRequired: false,
    layer: 'base',
    collapsible: true,
    resizable: true,
    focusTrap: false,
  },
  SecondarySidebar: {
    role: 'SecondarySidebar',
    type: 'Panel',
    direction: 'vertical',
    sizeMode: 'narrow',
    scrollAxis: 'y',
    defaultDensity: 'Compact',
    allowHero: false,
    maxDepth: 3,
    preferIconOnly: false,
    truncateText: true,
    tooltipRequired: false,
    layer: 'base',
    collapsible: true,
    resizable: true,
    focusTrap: false,
  },
  Editor: {
    role: 'Editor',
    type: 'Stage',
    direction: 'vertical',
    sizeMode: 'flexible',
    scrollAxis: 'both',
    defaultDensity: 'Standard',
    allowHero: false,
    maxDepth: 0,
    preferIconOnly: false,
    truncateText: false,
    tooltipRequired: false,
    layer: 'base',
    collapsible: false,
    resizable: false,
    focusTrap: false,
  },
  Master: {
    role: 'Master',
    type: 'Panel',
    direction: 'vertical',
    sizeMode: 'narrow',
    scrollAxis: 'y',
    defaultDensity: 'Compact',
    allowHero: false,
    maxDepth: 3,
    preferIconOnly: false,
    truncateText: true,
    tooltipRequired: false,
    layer: 'base',
    collapsible: false,
    resizable: true,
    focusTrap: false,
  },
  Detail: {
    role: 'Detail',
    type: 'Panel',
    direction: 'vertical',
    sizeMode: 'flexible',
    scrollAxis: 'y',
    defaultDensity: 'Standard',
    allowHero: false,
    maxDepth: 0,
    preferIconOnly: false,
    truncateText: false,
    tooltipRequired: false,
    layer: 'base',
    collapsible: false,
    resizable: false,
    focusTrap: false,
  },
  DialogHeader: {
    role: 'DialogHeader',
    type: 'Bar',
    direction: 'horizontal',
    sizeMode: 'fixed',
    scrollAxis: 'none',
    defaultDensity: 'Comfortable',
    allowHero: false,
    maxDepth: 1,
    preferIconOnly: false,
    truncateText: true,
    tooltipRequired: false,
    layer: 'modal',
    collapsible: false,
    resizable: false,
    focusTrap: false,
  },
  DialogContent: {
    role: 'DialogContent',
    type: 'Stage',
    direction: 'vertical',
    sizeMode: 'flexible',
    scrollAxis: 'y',
    defaultDensity: 'Comfortable',
    allowHero: false,
    maxDepth: 0,
    preferIconOnly: false,
    truncateText: false,
    tooltipRequired: false,
    layer: 'modal',
    collapsible: false,
    resizable: false,
    focusTrap: false,
  },
  DialogFooter: {
    role: 'DialogFooter',
    type: 'Bar',
    direction: 'horizontal',
    sizeMode: 'fixed',
    scrollAxis: 'none',
    defaultDensity: 'Comfortable',
    allowHero: false,
    maxDepth: 1,
    preferIconOnly: false,
    truncateText: false,
    tooltipRequired: false,
    layer: 'modal',
    collapsible: false,
    resizable: false,
    focusTrap: false,
  },
  Nav: {
    role: 'Nav',
    type: 'Panel',
    direction: 'vertical',
    sizeMode: 'narrow',
    scrollAxis: 'y',
    defaultDensity: 'Compact',
    allowHero: false,
    maxDepth: 3,
    preferIconOnly: false,
    truncateText: true,
    tooltipRequired: false,
    layer: 'base',
    collapsible: true,
    resizable: false,
    focusTrap: false,
  },
  Status: {
    role: 'Status',
    type: 'Bar',
    direction: 'horizontal',
    sizeMode: 'fixed',
    scrollAxis: 'none',
    defaultDensity: 'Compact',
    allowHero: false,
    maxDepth: 1,
    preferIconOnly: true,
    truncateText: true,
    tooltipRequired: false,
    layer: 'base',
    collapsible: false,
    resizable: false,
    focusTrap: false,
  },
  Dock: {
    role: 'Dock',
    type: 'Bar',
    direction: 'horizontal',
    sizeMode: 'fixed',
    scrollAxis: 'none',
    defaultDensity: 'Compact',
    allowHero: false,
    maxDepth: 1,
    preferIconOnly: true,
    truncateText: true,
    tooltipRequired: false,
    layer: 'base',
    collapsible: false,
    resizable: false,
    focusTrap: false,
  },
};

/**
 * Section Validation Rules
 */
export const SECTION_RULES: Record<SectionRole, SectionRules> = {
  // === Bar ===
  Header: {
    allowed: {
      blocks: ['Toolbar', 'Breadcrumbs', 'Tabs', 'Navigation', 'Group', 'Row', 'Divider'],
      elements: ['Text:Title', 'Text:Label', 'Action', 'Image', 'Field:SearchInput'],
    },
    forbidden: {
      blocks: ['Form', 'DataTable', 'TreeView', 'Card', 'EmptyState'],
      elements: ['Field:TextArea', 'Video'],
      prominences: ['Hero'],
    },
    constraints: { maxDepth: 2, maxActions: 5 },
  },
  Footer: {
    allowed: {
      blocks: ['Group', 'Row', 'Divider'],
      elements: ['Text:Caption', 'Action', 'Image:Icon'],
    },
    forbidden: {
      blocks: ['Form', 'DataTable', 'TreeView', 'Card', 'List'],
      elements: ['Field', 'Video'],
      prominences: ['Hero'],
    },
    constraints: { maxDepth: 2 },
  },
  Toolbar: {
    allowed: {
      blocks: ['Group', 'Row', 'DividerVertical'],
      elements: ['Action', 'Field:Select', 'Field:SearchInput', 'Separator'],
    },
    forbidden: {
      blocks: ['Card', 'List', 'Form', 'DataTable', 'TreeView'],
      elements: ['Text:Body', 'Text:Heading', 'Field:TextArea', 'Image', 'Video'],
    },
    constraints: { maxDepth: 1, direction: 'horizontal', iconOnly: true, tooltipRequired: true },
  },
  Statusbar: {
    allowed: {
      blocks: ['Group', 'Row'],
      elements: ['Text:Caption', 'Action', 'Image:Icon', 'Text:Progress'],
    },
    forbidden: {
      blocks: ['Card', 'List', 'Form', 'DataTable', 'TreeView', 'Navigation'],
      elements: ['Field', 'Video'],
      prominences: ['Hero'],
    },
    constraints: { maxDepth: 1, direction: 'horizontal' },
  },
  Tabbar: {
    allowed: {
      blocks: ['Group', 'Row'],
      elements: ['Action'],
    },
    forbidden: {
      blocks: ['*'], // Only Actions basically
      elements: ['Text', 'Field', 'Image', 'Video'],
    },
    constraints: { maxDepth: 1, direction: 'horizontal', iconOnly: true, tooltipRequired: true },
  },

  // === Panel ===
  Sidebar: {
    allowed: {
      blocks: ['List', 'TreeView', 'Card', 'Stack', 'Group', 'Navigation', 'Accordion'],
      elements: ['Text', 'Action', 'Image', 'Field:SearchInput', 'Separator'],
    },
    forbidden: {
      blocks: ['DataTable', 'GridLayout', 'Canvas'],
      prominences: ['Hero'],
    },
    restricted: {
      data: ['List', 'TreeView'],
      form: ['FilterBar'],
    },
    constraints: { maxDepth: 3, maxWidth: 320 },
  },
  Rail: {
    allowed: {
      blocks: ['Stack', 'Group'],
      elements: ['Action', 'Separator', 'Image:Avatar'],
    },
    forbidden: {
      blocks: ['*'],
      elements: ['Text', 'Field', 'Video'],
    },
    constraints: { maxDepth: 1, iconOnly: true, tooltipRequired: true, fixedWidth: 64 },
  },
  Aside: {
    allowed: { blocks: '*', elements: '*' },
    forbidden: { blocks: ['Canvas'], prominences: ['Hero'] },
    constraints: { maxDepth: 4 },
  },
  Panel: {
    allowed: { blocks: '*', elements: '*' },
    forbidden: { blocks: ['Canvas'], prominences: ['Hero'] },
    constraints: { maxDepth: 4 },
  },

  // === Main ===
  Main: {
    allowed: { blocks: '*', elements: '*' },
    forbidden: { blocks: [], elements: [] },
    constraints: { maxDepth: 99 },
  },
  Canvas: {
    allowed: { blocks: '*', elements: '*' },
    forbidden: { blocks: ['List', 'TreeView'], elements: [] }, // Lists/Trees don't make sense in free-form canvas usually without container
    constraints: { maxDepth: 99 },
  },
  Content: {
    allowed: { blocks: '*', elements: '*' },
    forbidden: { blocks: [], elements: [] },
    constraints: { maxDepth: 99, maxWidth: 800 }, // Readable width
  },

  // === Overlay ===
  Modal: {
    allowed: { blocks: '*', elements: '*' },
    forbidden: { blocks: ['Canvas'], elements: [] },
    required: { closeAction: true, name: true },
    constraints: { maxWidth: 640, focusTrap: true, maxDepth: 4 },
  },
  Toast: {
    allowed: {
      blocks: ['Group', 'Row'],
      elements: ['Text:Body', 'Text:Caption', 'Action', 'Image:Icon'],
    },
    forbidden: {
      blocks: ['Card', 'List', 'Form', 'DataTable', 'TreeView'],
      elements: ['Field', 'Video', 'Text:Title', 'Text:Heading'],
    },
    constraints: { maxDepth: 1, maxActions: 2, maxTextLength: 100, autoDismiss: true },
  },
  Drawer: {
    allowed: { blocks: '*', elements: '*' },
    forbidden: { blocks: ['Canvas'], elements: [] },
    constraints: { maxDepth: 3, focusTrap: true },
  },
  Sheet: {
    allowed: { blocks: '*', elements: '*' },
    forbidden: { blocks: ['Canvas'], elements: [] },
    constraints: { maxDepth: 3, focusTrap: true },
  },
  Popover: {
    allowed: {
      blocks: ['Menu', 'List', 'Group', 'Stack'],
      elements: ['Action', 'Text:Label', 'Text:Caption', 'Field:Select', 'Separator'],
    },
    forbidden: {
      blocks: ['DataTable', 'Form', 'Card', 'TreeView'],
      elements: ['Video', 'Image:Large'],
    },
    restricted: { layout: ['Group', 'Stack'], form: ['FieldGroup'] },
    constraints: { maxDepth: 2, maxItems: 10 },
  },

  // === Landmark ===
  Navigation: {
    allowed: { blocks: '*', elements: '*' },
    forbidden: { blocks: [], elements: [] },
    constraints: { maxDepth: 2 },
  },
  Search: {
    allowed: { blocks: '*', elements: '*' },
    forbidden: { blocks: [], elements: [] },
    constraints: { maxDepth: 3 },
  },
  Region: {
    allowed: { blocks: '*', elements: '*' },
    forbidden: { blocks: [], elements: [] },
    constraints: { maxDepth: 4 },
  },

  // === Extensions (Defaults to loose rules) ===
  Navigator: {
    allowed: { blocks: '*', elements: '*' },
    forbidden: { blocks: [], elements: [] },
    constraints: { maxDepth: 3 },
  },
  Container: {
    allowed: { blocks: '*', elements: '*' },
    forbidden: { blocks: [], elements: [] },
    constraints: { maxDepth: 99 },
  },
  ActivityBar: {
    allowed: { blocks: ['Stack'], elements: ['Action', 'Image:Avatar'] },
    forbidden: { blocks: [], elements: [] },
    constraints: { maxDepth: 1, iconOnly: true },
  },
  UtilityBar: {
    allowed: { blocks: ['Row'], elements: ['Action'] },
    forbidden: { blocks: [], elements: [] },
    constraints: { maxDepth: 1 },
  },
  PrimarySidebar: {
    allowed: { blocks: '*', elements: '*' },
    forbidden: { blocks: [], elements: [] },
    constraints: { maxDepth: 3 },
  },
  SecondarySidebar: {
    allowed: { blocks: '*', elements: '*' },
    forbidden: { blocks: [], elements: [] },
    constraints: { maxDepth: 3 },
  },
  Editor: {
    allowed: { blocks: '*', elements: '*' },
    forbidden: { blocks: [], elements: [] },
    constraints: { maxDepth: 99 },
  },
  Master: {
    allowed: { blocks: '*', elements: '*' },
    forbidden: { blocks: [], elements: [] },
    constraints: { maxDepth: 3 },
  },
  Detail: {
    allowed: { blocks: '*', elements: '*' },
    forbidden: { blocks: [], elements: [] },
    constraints: { maxDepth: 99 },
  },
  DialogHeader: {
    allowed: { blocks: ['Row', 'Group'], elements: ['Text:Title', 'Action'] },
    forbidden: { blocks: ['*'], elements: ['*'] },
    constraints: { maxDepth: 1 },
  },
  DialogContent: {
    allowed: { blocks: '*', elements: '*' },
    forbidden: { blocks: [], elements: [] },
    constraints: { maxDepth: 99 },
  },
  DialogFooter: {
    allowed: { blocks: ['Row'], elements: ['Action'] },
    forbidden: { blocks: ['*'], elements: ['*'] },
    constraints: { maxDepth: 1 },
  },
  Nav: {
    allowed: { blocks: '*', elements: '*' },
    forbidden: { blocks: [], elements: [] },
    constraints: { maxDepth: 3 },
  },
  Status: {
    allowed: { blocks: ['Row'], elements: ['Action', 'Text:Caption'] },
    forbidden: { blocks: ['*'], elements: ['*'] },
    constraints: { maxDepth: 1 },
  },
  Dock: {
    allowed: { blocks: ['Row'], elements: ['Action'] },
    forbidden: { blocks: ['*'], elements: ['*'] },
    constraints: { maxDepth: 1 },
  },
};
