/**
 * ✨ AUTOMATICALLY GENERATED - DO NOT EDIT ✨
 * 
 * Generated by scripts/generate-layout.ts
 * Source: layout.config.ts
 */

import type React from "react";
import type { FrameOverrides } from "../FrameProps.ts";

/**
 * 🔒 Layout Type Guardrails
 */
declare const LayoutTokenBrand: unique symbol;

export type LayoutToken = FrameOverrides & { 
  readonly [LayoutTokenBrand]: true;
  style?: React.CSSProperties;
};

/**
 * Variable Definitions (Hoisted)
 * Flattened chain of property objects to reduce duplication.
 */
const _Row = { row: true };
const _Row_Top = { ..._Row, align: "start" };
const _Row_Top_Start = { ..._Row_Top, pack: "start" };
const _Row_Top_Center = { ..._Row_Top, pack: "center" };
const _Row_Top_End = { ..._Row_Top, pack: "end" };
const _Row_Top_Between = { ..._Row_Top, pack: "space" };
const _Row_Middle = { ..._Row, align: "center" };
const _Row_Middle_Start = { ..._Row_Middle, pack: "start" };
const _Row_Middle_Center = { ..._Row_Middle, pack: "center" };
const _Row_Middle_End = { ..._Row_Middle, pack: "end" };
const _Row_Middle_Between = { ..._Row_Middle, pack: "space" };
const _Row_Bottom = { ..._Row, align: "end" };
const _Row_Bottom_Start = { ..._Row_Bottom, pack: "start" };
const _Row_Bottom_Center = { ..._Row_Bottom, pack: "center" };
const _Row_Bottom_End = { ..._Row_Bottom, pack: "end" };
const _Row_Bottom_Between = { ..._Row_Bottom, pack: "space" };
const _Row_Stretch = { ..._Row, align: "stretch" };
const _Row_Stretch_Start = { ..._Row_Stretch, pack: "start" };
const _Row_Stretch_Center = { ..._Row_Stretch, pack: "center" };
const _Row_Stretch_End = { ..._Row_Stretch, pack: "end" };
const _Row_Stretch_Between = { ..._Row_Stretch, pack: "space" };
const _Row_Baseline = _Row;
const _Row_Baseline_Start = { ..._Row_Baseline, pack: "start" };
const _Row_Baseline_Center = { ..._Row_Baseline, pack: "center" };
const _Row_Baseline_End = { ..._Row_Baseline, pack: "end" };
const _Row_Baseline_Between = { ..._Row_Baseline, pack: "space" };
const _Col = {  };
const _Col_Left = { ..._Col, align: "start" };
const _Col_Left_Start = { ..._Col_Left, pack: "start" };
const _Col_Left_Center = { ..._Col_Left, pack: "center" };
const _Col_Left_End = { ..._Col_Left, pack: "end" };
const _Col_Left_Between = { ..._Col_Left, pack: "space" };
const _Col_Center = { ..._Col, align: "center" };
const _Col_Center_Start = { ..._Col_Center, pack: "start" };
const _Col_Center_Center = { ..._Col_Center, pack: "center" };
const _Col_Center_End = { ..._Col_Center, pack: "end" };
const _Col_Center_Between = { ..._Col_Center, pack: "space" };
const _Col_Right = { ..._Col, align: "end" };
const _Col_Right_Start = { ..._Col_Right, pack: "start" };
const _Col_Right_Center = { ..._Col_Right, pack: "center" };
const _Col_Right_End = { ..._Col_Right, pack: "end" };
const _Col_Right_Between = { ..._Col_Right, pack: "space" };
const _Col_Stretch = { ..._Col, align: "stretch" };
const _Col_Stretch_Start = { ..._Col_Stretch, pack: "start" };
const _Col_Stretch_Center = { ..._Col_Stretch, pack: "center" };
const _Col_Stretch_End = { ..._Col_Stretch, pack: "end" };
const _Col_Stretch_Between = { ..._Col_Stretch, pack: "space" };

/**
 * Internal Factory ensures safe casting.
 */
function defineLayout<P, C>(props: P, children: C = {} as C): P & C & LayoutToken {
  return { ...props, ...children } as P & C & LayoutToken;
}

export const Layout = {
  Row: defineLayout(_Row, {
    Top: defineLayout(_Row_Top, {
      Start: defineLayout(_Row_Top_Start),
      Center: defineLayout(_Row_Top_Center),
      End: defineLayout(_Row_Top_End),
      Between: defineLayout(_Row_Top_Between),
    }),
    Middle: defineLayout(_Row_Middle, {
      Start: defineLayout(_Row_Middle_Start),
      Center: defineLayout(_Row_Middle_Center),
      End: defineLayout(_Row_Middle_End),
      Between: defineLayout(_Row_Middle_Between),
    }),
    Bottom: defineLayout(_Row_Bottom, {
      Start: defineLayout(_Row_Bottom_Start),
      Center: defineLayout(_Row_Bottom_Center),
      End: defineLayout(_Row_Bottom_End),
      Between: defineLayout(_Row_Bottom_Between),
    }),
    Stretch: defineLayout(_Row_Stretch, {
      Start: defineLayout(_Row_Stretch_Start),
      Center: defineLayout(_Row_Stretch_Center),
      End: defineLayout(_Row_Stretch_End),
      Between: defineLayout(_Row_Stretch_Between),
    }),
    Baseline: defineLayout(_Row_Baseline, {
      Start: defineLayout(_Row_Baseline_Start),
      Center: defineLayout(_Row_Baseline_Center),
      End: defineLayout(_Row_Baseline_End),
      Between: defineLayout(_Row_Baseline_Between),
    }),
  }),
  Col: defineLayout(_Col, {
    Left: defineLayout(_Col_Left, {
      Start: defineLayout(_Col_Left_Start),
      Center: defineLayout(_Col_Left_Center),
      End: defineLayout(_Col_Left_End),
      Between: defineLayout(_Col_Left_Between),
    }),
    Center: defineLayout(_Col_Center, {
      Start: defineLayout(_Col_Center_Start),
      Center: defineLayout(_Col_Center_Center),
      End: defineLayout(_Col_Center_End),
      Between: defineLayout(_Col_Center_Between),
    }),
    Right: defineLayout(_Col_Right, {
      Start: defineLayout(_Col_Right_Start),
      Center: defineLayout(_Col_Right_Center),
      End: defineLayout(_Col_Right_End),
      Between: defineLayout(_Col_Right_Between),
    }),
    Stretch: defineLayout(_Col_Stretch, {
      Start: defineLayout(_Col_Stretch_Start),
      Center: defineLayout(_Col_Stretch_Center),
      End: defineLayout(_Col_Stretch_End),
      Between: defineLayout(_Col_Stretch_Between),
    }),
  }),
} as const;
